version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/laravel-app
permissions:
  - object: /var/www/laravel-app
    pattern: '**/*'
    owner: www-data
    group: www-data
    mode: 775
hooks:
  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 300
      runas: root

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

  ApplicationStart:
    - location: scripts/restart_server.sh
      timeout: 300
      runas: root

  ValidateService:
    - location: scripts/health_check.sh
      timeout: 300
      runas: root
