version: 0.0
os: linux
files:
  - source: .
    destination: /var/www/expressud

hooks:
  BeforeInstall:
    - location: scripts/setup_php.sh
      timeout: 600
      runas: ubuntu

  AfterInstall:
    - location: scripts/install.sh
      timeout: 600
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
