version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
      nodejs: 18
    commands:
      - echo Installing Composer...
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo Installing project dependencies...
      - cd backend
      - composer install --no-interaction --prefer-dist --optimize-autoloader

  build:
    commands:
      - echo Build phase complete

  post_build:
    commands:
      - echo Build completed on $(date)
      - chmod +x scripts/install.sh
      - chmod +x scripts/start.sh

artifacts:
  files:
    - '**/*'
  base-directory: backend

