version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - set -x
      - echo "Installing system dependencies..."
      - yum install -y git unzip
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer

  pre_build:
    commands:
      - set -x
      - echo "Fetching environment variables from AWS Parameter Store..."
      # Ensure all required environment variables are fetched and logged
      - |
        export DB_HOST=$(aws ssm get-parameter --name "/expressuddb/db_host" --query Parameter.Value --output text 2>&1)
        echo "DB_HOST: $DB_HOST"
      - |
        export DB_DATABASE=$(aws ssm get-parameter --name "/expressuddb/db_name" --query Parameter.Value --output text 2>&1)
        echo "DB_DATABASE: $DB_DATABASE"
      - |
        export DB_USERNAME=$(aws ssm get-parameter --name "/expressuddb/db_user" --query Parameter.Value --output text 2>&1)
        echo "DB_USERNAME: $DB_USERNAME"
      - |
        export DB_PASSWORD=$(aws ssm get-parameter --name "/expressuddb/db_password" --with-decryption --query Parameter.Value --output text 2>&1)
        echo "DB_PASSWORD retrieved successfully"
      - export DB_PORT=3306
      - echo "DB_PORT: $DB_PORT"

      # Debugging output for environment variable status
      - echo "Loaded environment variables:"
      - env | grep DB_

      # Setup Laravel environment file
      - echo "Setting up Laravel environment..."
      - |
        cp $CODEBUILD_SRC_DIR/backend/.env.example $CODEBUILD_SRC_DIR/backend/.env &&
        printf '%s\n' "DB_CONNECTION=mysql" >> $CODEBUILD_SRC_DIR/backend/.env &&
        sed -i "s|DB_HOST=.*|DB_HOST=\"$DB_HOST\"|" $CODEBUILD_SRC_DIR/backend/.env &&
        sed -i "s|DB_DATABASE=.*|DB_DATABASE=\"$DB_DATABASE\"|" $CODEBUILD_SRC_DIR/backend/.env &&
        sed -i "s|DB_USERNAME=.*|DB_USERNAME=\"$DB_USERNAME\"|" $CODEBUILD_SRC_DIR/backend/.env &&
        printf '%s\n' "DB_PASSWORD=\"$DB_PASSWORD\"" >> $CODEBUILD_SRC_DIR/backend/.env
      - echo "Laravel environment file configured."

      # Install PHP dependencies
      - echo "Installing PHP dependencies..."
      - cd $CODEBUILD_SRC_DIR/backend
      - rm -rf vendor
      - composer install --no-dev --optimize-autoloader

  build:
    commands:
      - set -x
      - echo "Build phase complete. Nothing to build for Laravel."

  post_build:
    commands:
      - set -x
      - echo "Testing database connectivity..."
      - yum install -y nmap-ncat

      # Validate database connectivity
      - |
        if nc -zv $DB_HOST $DB_PORT; then
          echo "Successfully connected to the database at $DB_HOST:$DB_PORT."
        else
          echo "Failed to connect to the database at $DB_HOST:$DB_PORT."
          exit 1
        fi

      # Display .env file contents for verification
      - echo "Current .env file:"
      - cat $CODEBUILD_SRC_DIR/backend/.env

      # Laravel post-build steps
      - echo "Clearing Laravel caches..."
      - php artisan cache:clear
      - php artisan config:clear
      - php artisan config:cache
      - php artisan route:clear
      - php artisan route:cache
      - echo "Running database migrations..."
      - php artisan migrate --force

artifacts:
  files:
    - '**/*'
  base-directory: backend
  discard-paths: no

  