version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Server deploy build: no Laravel commands here."
  build:
    commands:
      - echo "Packaging backend for CodeDeploy"
  post_build:
    commands:
      - chmod +x scripts/setup_system.sh
      - chmod +x scripts/install.sh
      - chmod +x scripts/start.sh

artifacts:
  files:
    - '**/*'
  base-directory: 'backend'
