version: 0.2

phases:
  install:
    commands:
      - echo "Updating system dependencies..."
      - sudo dnf update -y
      - echo "Adding MySQL repository..."
      - sudo rpm --import https://repo.mysql.com/RPM-GPG-KEY-mysql-2022
      - sudo dnf install -y https://dev.mysql.com/get/mysql80-community-release-el9-1.noarch.rpm
      - sudo dnf config-manager --enable mysql80-community
      - echo "Installing MySQL client..."
      - |
        if ! sudo dnf install -y mysql-community-client --nogpgcheck; then
          echo "Falling back to alternate MySQL client package..."
          sudo dnf install -y mysql
        fi
      - echo "MySQL client installed successfully."

  pre_build:
    commands:
      - echo "Fetching environment variables from AWS Parameter Store..."
      - set +x  # Disable logging of sensitive commands
      - export DB_HOST=$(aws ssm get-parameter --name "/expressuddb/db_host" --query Parameter.Value --output text)
      - export DB_PORT=$(aws ssm get-parameter --name "/expressuddb/db_port" --query Parameter.Value --output text)
      - export DB_DATABASE=$(aws ssm get-parameter --name "/expressuddb/db_name" --query Parameter.Value --output text)
      - export DB_USERNAME=$(aws ssm get-parameter --name "/expressuddb/db_user" --query Parameter.Value --output text)
      - export DB_PASSWORD=$(aws ssm get-parameter --name "/expressuddb/db_password" --with-decryption --query Parameter.Value --output text)
      - set -x  # Re-enable logging
      - echo "Environment variables loaded successfully."

      - echo "Testing database connectivity..."
      - |
        if mysql -h "$DB_HOST" -P "$DB_PORT" -u "$DB_USERNAME" -p"$DB_PASSWORD" -e "SHOW DATABASES;"; then
          echo "Successfully connected to the database."
        else
          echo "Failed to connect to the database. Debugging information:"
          echo "Host: $DB_HOST"
          echo "Port: $DB_PORT"
          echo "Database: $DB_DATABASE"
          echo "Username: $DB_USERNAME"
          exit 1
        fi

  build:
    commands:
      - echo "Building the application..."
      - composer install --no-dev --optimize-autoloader
      - echo "Application built successfully."

  post_build:
    commands:
      - echo "Post-build steps completed."

artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*'
  base-directory: /codebuild/output/src

cache:
  paths:
    - '/root/.composer/cache'
