version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing system dependencies..."
      - yum install -y git unzip
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer

  pre_build:
    commands:
      - echo "Checking and setting execute permissions for pre-build script..."
      - chmod +x ./scripts/Pre_build.sh
      - ./scripts/pre_build.sh

  build:
    commands:
      - echo "Build phase complete. Nothing to build for Laravel."

  post_build:
    commands:
      - echo "Checking and setting execute permissions for post-build script..."
      - chmod +x ./scripts/post_build.sh
      - ./scripts/post_build.sh

artifacts:
  files:
    - '**/*'
  base-directory: backend
  discard-paths: no
