version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - cd $CODEBUILD_SRC_DIR/backend
      - composer install --no-dev --optimize-autoloader
      - npm install
  pre_build:
    commands:
      - echo Preparing Laravel...
      - cp .env.example .env || true
      - php artisan config:clear || true
  build:
    commands:
      - echo Building the Laravel app...
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: 'backend'
