version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing system dependencies..."
      - sudo dnf update -y
      - sudo yum install -y git unzip
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Dependencies installed successfully."

  pre_build:
    commands:
      - echo "Fetching database credentials from AWS Secrets Manager..."
      - set +x  # Disable logging of sensitive information
      - SECRET=$(aws secretsmanager get-secret-value --secret-id rds!db-3b364449-a25b-4d2a-9c10-e5f1bf691a12 --query SecretString --output text)
      - export DB_HOST=$(echo $SECRET | jq -r '.db_host')
      - export DB_PORT=$(echo $SECRET | jq -r '.db_port')
      - export DB_DATABASE=$(echo $SECRET | jq -r '.db_name')
      - export DB_USERNAME=$(echo $SECRET | jq -r '.db_user')
      - export DB_PASSWORD=$(echo $SECRET | jq -r '.db_password')
      - set -x  # Re-enable logging
      - echo "Database credentials loaded successfully."

      - echo "Configuring Laravel environment..."
      - cp "$CODEBUILD_SRC_DIR/backend/.env.example" "$CODEBUILD_SRC_DIR/backend/.env"
      - sed -i "s|DB_HOST=.*|DB_HOST=$DB_HOST|" "$CODEBUILD_SRC_DIR/backend/.env"
      - sed -i "s|DB_PORT=.*|DB_PORT=$DB_PORT|" "$CODEBUILD_SRC_DIR/backend/.env"
      - sed -i "s|DB_DATABASE=.*|DB_DATABASE=$DB_DATABASE|" "$CODEBUILD_SRC_DIR/backend/.env"
      - sed -i "s|DB_USERNAME=.*|DB_USERNAME=$DB_USERNAME|" "$CODEBUILD_SRC_DIR/backend/.env"
      - sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=$DB_PASSWORD|" "$CODEBUILD_SRC_DIR/backend/.env"
      - echo "Laravel environment configured successfully."

  build:
    commands:
      - echo "Installing Laravel dependencies..."
      - cd "$CODEBUILD_SRC_DIR/backend"
      - composer install --no-dev --optimize-autoloader
      - echo "Building optimized application..."
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      - echo "Application build completed."

  post_build:
    commands:
      - echo "Testing database connectivity..."
      - yum install -y nmap-ncat
      - |
        if nc -zv "$DB_HOST" "$DB_PORT"; then
          echo "Database connection successful."
        else
          echo "Failed to connect to the database."
          exit 1
        fi
      - echo "Running database migrations..."
      - php artisan migrate --force
      - echo "Post-build steps completed successfully."

artifacts:
  files:
    - '**/*'
  base-directory: backend
  discard-paths: no

cache:
  paths:
    - '/root/.composer/cache'