version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - echo "Composer installed"
      
  pre_build:
    commands:
      - echo "Installing project dependencies..."
      - composer install --no-interaction --prefer-dist --optimize-autoloader
      - echo "Dependencies installed"

  build:
    commands:
      - echo "Running Laravel optimizations..."
      - php artisan config:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
      # Optional: Uncomment to run DB migrations automatically
      # - php artisan migrate --force

  post_build:
    commands:
      - echo "Build complete on `date`"
      - echo "Artifacts ready for deployment"

artifacts:
  files:
    - '**/*'
  base-directory: .
