version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing system dependencies..."
      - sudo yum update -y
      - sudo yum install -y unzip git nmap mariadb
      - echo "Installing Composer..."
      - curl -sS https://getcomposer.org/installer | php
      - sudo mv composer.phar /usr/local/bin/composer

  pre_build:
    commands:
      - echo "Fetching environment variables from Parameter Store..."
      - export DB_HOST=$(aws ssm get-parameter --name "/expressuddb/db_host" --query Parameter.Value --output text)
      - export DB_PORT=$(aws ssm get-parameter --name "/expressuddb/db_port" --query Parameter.Value --output text)
      - export DB_DATABASE=$(aws ssm get-parameter --name "/expressuddb/db_name" --query Parameter.Value --output text)
      - export DB_USERNAME=$(aws ssm get-parameter --name "/expressuddb/db_user" --query Parameter.Value --output text)
      - export DB_PASSWORD=$(aws ssm get-parameter --name "/expressuddb/db_password" --with-decryption --query Parameter.Value --output text)
      - echo "Environment variables loaded successfully."

      - echo "Testing database connectivity..."
      - if nc -zv "$DB_HOST" "$DB_PORT"; then echo "Successfully connected to the database."; else echo "Failed to connect to the database."; exit 1; fi

      - echo "Setting up Laravel environment..."
      - cp .env.example .env
      - sed -i "s|DB_HOST=.*|DB_HOST=$DB_HOST|g" .env
      - sed -i "s|DB_PORT=.*|DB_PORT=$DB_PORT|g" .env
      - sed -i "s|DB_DATABASE=.*|DB_DATABASE=$DB_DATABASE|g" .env
      - sed -i "s|DB_USERNAME=.*|DB_USERNAME=$DB_USERNAME|g" .env
      - sed -i "s|DB_PASSWORD=.*|DB_PASSWORD=$DB_PASSWORD|g" .env

  build:
    commands:
      - echo "Running Laravel deployment steps..."
      - composer install --no-dev --optimize-autoloader
      - php artisan config:clear
      - php artisan cache:clear
      - php artisan config:cache
      - php artisan route:cache
      - php artisan migrate --force
      - echo "Laravel deployment completed successfully."

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: /var/www/html
  discard-paths: no
