version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing dependencies"
      - yum install -y git unzip

  build:
    commands:
      - echo "Build phase"

artifacts:
  files:
    - '**/*'
  base-directory: backend
  discard-paths: no
