version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - echo Installing source NPM dependencies...
      - ls -la  # Check contents of root directory
      - ls -la $CODEBUILD_SRC_DIR  # Check if source directory exists
      - ls -la $CODEBUILD_SRC_DIR/Expressud  # Check if 'Expressud' exists
      - cd $CODEBUILD_SRC_DIR/Expressud/driver
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo "Changing to the correct directory"
      - ls -la $CODEBUILD_SRC_DIR/Expressud  # Check if 'Expressud' directory exists
      - cd $CODEBUILD_SRC_DIR/Expressud/driver  # Use CODEBUILD_SRC_DIR for absolute path
      - ls -la  # Check contents to confirm successful navigation
      - ng build --prod --output-path=dist/driver

  post_build:
    commands:
      - echo Build completed on $(date)
