version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - echo Installing source NPM dependencies...
      - ls -la  # Check contents of root directory
      - ls -la Expressud  # Check if 'Expressud' exists
      - ls -la Expressud/driver  # Check if 'driver' exists

      - cd Expressud/driver
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Build started
      - ls -la Expressud  # Check 'Expressud' directory again
      - ls -la Expressud/driver  # Check if 'driver' exists before building
      - cd Expressud/driver
      - ng build --prod --output-path=dist/driver

  post_build:
    commands:
      - echo Build completed on $(date)
