version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing source NPM dependencies...
      - cd Expressud/driver  # Navigate to the directory containing package.json
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started 
      - ng build --prod --output-path=dist/driver # adjust per project

