version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - echo Installing source NPM dependencies...
            - ls -la  # Debugging step to check the directory contents
      - cd Express/Expressud/driver

      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Build started
      - cd Express/Expressud/driver

      - ng build --prod --output-path=dist/driver

  post_build:
    commands:
      - echo Build completed on $(date)
