version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - echo Installing source NPM dependencies...
      - cd $CODEBUILD_SRC_DIR/Expressud
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Build started
      - cd $CODEBUILD_SRC_DIR/Expressud
      - ng build --configuration production --output-path=dist/expressud

  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - '**/*'                          # Include all files within the base directory
  base-directory: 'Expressud/dist/expressud'  # Adjusted to match the output path

