version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - echo Installing source NPM dependencies...
      - cd Expressud/expressud
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Build started
      - cd Expressud/expressud
      - ng build --prod --output-path=dist/expressud

  post_build:
    commands:
      - echo Build completed on $(date)
