version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - echo Installing source NPM dependencies...
      - cd $CODEBUILD_SRC_DIR/admin-panel
      - npm ci --legacy-peer-deps

  pre_build:
    commands:
      - echo "===== angular.json (verify fileReplacements for production) ====="
      - cd $CODEBUILD_SRC_DIR/admin-panel
      - node -e "const fs=require('fs');const j=JSON.parse(fs.readFileSync('angular.json','utf8'));const p=Object.keys(j.projects)[0];console.log(JSON.stringify(j.projects[p].architect.build.configurations.production.fileReplacements,null,2))"
      - echo "===== src/environments/environment.prod.ts (first 200 lines) ====="
      - sed -n '1,200p' src/environments/environment.prod.ts || true

  build:
    commands:
      - echo Build started
      - cd $CODEBUILD_SRC_DIR/admin-panel
      - ng build --configuration production --output-path=dist/admin-panel

  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - '**/*'
  base-directory: 'admin-panel/dist/admin-panel'
