version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - echo Installing source NPM dependencies...
      - cd $CODEBUILD_SRC_DIR/admin-panel
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Build started
      - cd $CODEBUILD_SRC_DIR/admin-panel
      - ng build --configuration production --output-path=dist/admin-panel
      - echo Build completed

  post_build:
    commands:
      - echo "Syncing build to S3 root..."
      - aws s3 sync dist/admin-panel s3://expressud-admin/ --delete
      - echo "Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id ERSFMXPFX8HL9 --paths "/*"
