version: 0.2

env:
  variables:
    PANEL_DIR: "admin-panel"
    DIST_DIR: "admin-panel/dist/admin-panel"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "▶ Installing Angular CLI & deps"
      - npm i -g @angular/cli
      - cd "$CODEBUILD_SRC_DIR/$PANEL_DIR"
      - npm ci --legacy-peer-deps

  pre_build:
    commands:
      - echo "🔎 Checking SOURCE for forbidden localhost URLs (excluding environments files)..."
      - cd "$CODEBUILD_SRC_DIR/$PANEL_DIR"

      # Allow localhost ONLY inside environments/environment.ts (dev).
      # Fail if localhost appears anywhere else.
      - |
        if grep -R -n -E "localhost:8000|127\.0\.0\.1:8000" src/ \
          --exclude="environment.ts" \
          --exclude="environment.development.ts" \
          --exclude-dir="node_modules" \
          --exclude-dir="dist" ; then
          echo "❌ Found localhost in SOURCE outside environments/*.ts. Fix before building."
          exit 1
        else
          echo "✅ SOURCE clean (no localhost outside environments)."
        fi

      - echo "🔎 Ensuring you DON'T import environments/environment.prod directly..."
      - |
        if grep -R -n "environments/environment\.prod" src/ ; then
          echo "❌ Don't import environment.prod directly. Import 'environments/environment' instead."
          exit 1
        else
          echo "✅ No direct environment.prod imports."
        fi

  build:
    commands:
      - echo "🏗 Building PRODUCTION bundle..."
      - cd "$CODEBUILD_SRC_DIR/$PANEL_DIR"
      - ng build --configuration production --output-path=dist/admin-panel

  post_build:
    commands:
     - echo "🔍 Scanning built assets for localhost..."
      - cd "$CODEBUILD_SRC_DIR/$PANEL_DIR/dist/admin-panel"
      # FAIL if any localhost/127 calls remain (so we see it in logs)
      - if grep -R -n -E "http://(localhost|127\.0\.0\.1):8000" . ; then echo "❌ Found localhost in build. Rewriting..."; fi
      # Rewrite to prod API
      - find . -type f -name "*.js" -o -name "*.html" -o -name "*.json" -o -name "*.css" \
        | xargs -I{} sed -i -E 's#http://(localhost|127\.0\.0\.1):8000#https://api.expressud.com#g' {}
      # Verify again (now must be clean)
      - if grep -R -n -E "http://(localhost|127\.0\.0\.1):8000" . ; then echo "❌ Rewriter failed"; exit 1; else echo "✅ No localhost in build"; fi
artifacts:
  files:
    - '**/*'
  base-directory: 'admin-panel/dist/admin-panel'
