version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing Angular CLI...
      - npm install -g @angular/cli
      - echo Installing source NPM dependencies...
      - cd $CODEBUILD_SRC_DIR/driver
      - npm install --legacy-peer-deps

  build:
    commands:
      - echo Build started
      - cd $CODEBUILD_SRC_DIR/driver
      - ng build --configuration production --output-path=dist/driver
      - if [ -d dist/driver ]; then echo "Build directory exists"; else echo "Build directory not found"; exit 1; fi

  post_build:
    commands:
      - echo Build completed on $(date)

artifacts:
  files:
    - '**/*'
  base-directory: 'driver/dist/driver'
