version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo Installing system dependencies...
      - yum install -y git unzip
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
  pre_build:
    commands:
      - echo Installing PHP dependencies...
      - cd backendE  # Navigate to the Laravel project directory
      - composer install --no-dev --optimize-autoloader
  build:
    commands:
      - echo Build phase complete. Nothing to build for Laravel.
  post_build:
    commands:
      - echo Packaging application...
      - echo Running database migrations...
      - cd backendE  # Ensure you are in the Laravel directory
      - php artisan migrate --force  # Run migrations, the --force flag is required for production
artifacts:
  files:
    - '**/*'  # Include all files

# Optionally, you can define environment variables or use Secrets Manager for DB credentials
env:
  variables:
    DB_CONNECTION=mysql
    DB_HOST=expressuddb.cdswaw8i23c6.af-south-1.rds.amazonaws.com
    DB_PORT=3306
    DB_DATABASE=expressuddb
    DB_USERNAME=admin
    DB_PASSWORD=password
