service: backend-e

provider:
  name: aws
  runtime: provided.al2
  region: af-south-1
  environment:
    DB_HOST: ${ssm:/express/db/host}
    DB_DATABASE: ${ssm:/express/db/name}
    DB_USERNAME: ${ssm:/express/db/username}
    DB_PASSWORD: ${ssm:/express/db/password}

 iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ssm:GetParameter"
        - "ssm:GetParameters"
        - "ssm:GetParametersByPath"
      Resource:
        - "arn:aws:ssm:af-south-1:218381085969:parameter/express/db/*"   

functions:
  migrate:
    handler: vendor/bin/bref
    command: php artisan migrate --force
    layers:
      - ${bref:layer.php-81}
    events:
      - schedule:
          rate: rate(1 day)
