provider:
  name: aws
  runtime: provided.al2
  region: af-south-1

functions:
  migrate:
    handler: public/index.php
    layers:
      - ${bref:layer.php-81}  # Ensure you are using the correct PHP 8.1 layer from Bref
    environment:
      DB_HOST: expressuddb.cdswaw8i23c6.af-south-1.rds.amazonaws.com
      DB_DATABASE: expressuddb
      DB_USERNAME: admin
      DB_PASSWORD: 3|Y$(iC5.v7aX]A_a7>z9zNwOTbE
    events:
      - schedule:
          rate: rate(1 day)  # This schedules the migration to run daily (can be adjusted)
